export const DINO_API_DATA = [
  {
    "_id": "65ab56b3978ff91b1c9eb074",
    "name": "aardonyx",
    "weight": "1700kg",
    "height": "2m",
    "length": "8.0m",
    "diet": "herbivore",
    "period": "jurassic",
    "existed": "201.3 - 190.8 million years ago",
    "region": "south africa",
    "type": "terrestrial",
    "description": "Aardonyx is a genus of basal sauropodomorph dinosaur. It has arm features that are intermediate between prosauropods and sauropods, moving mainly on two legs but able to drop to four.",
    "image": "https://images.unsplash.com/photo-1516211697506-8360bd795160?auto=format&fit=crop&q=80&w=800",
    "isPopular": false
  },
  {
    "_id": "65ab5bbf978ff91b1c9eb076",
    "name": "abelisaurus",
    "weight": "3000kg",
    "height": "2m",
    "length": "7.4m",
    "diet": "carnivore",
    "period": "cretaceous",
    "existed": "83.5 - 70.6 million years ago",
    "region": "south america",
    "type": "terrestrial",
    "description": "A large theropod from Argentina, similar to the famous T-Rex but with a shorter, deeper skull. It was a fierce predator of its time.",
    "image": "https://images.unsplash.com/photo-1559999141-792646c05f56?auto=format&fit=crop&q=80&w=800",
    "isPopular": false
  },
  {
    "_id": "65ac155886621fdaf2c40bc1",
    "name": "abrictosaurus",
    "weight": "3kg",
    "height": "0.35m",
    "length": "1.2m",
    "diet": "herbivore/omnivore",
    "period": "early jurassic",
    "existed": "199 - 196 million years ago",
    "region": "south africa",
    "type": "terrestrial",
    "description": "A very small dinosaur with different types of teeth, including tusks! It was likely a fast runner that ate plants and small insects.",
    "image": "https://images.unsplash.com/photo-1620067902055-6b6680a6be1d?auto=format&fit=crop&q=80&w=800",
    "isPopular": false
  },
  {
    "_id": "65af1ecc784e13b0a5e697d3",
    "name": "acrocanthosaurus",
    "weight": "6000kg",
    "height": "4m",
    "length": "12m",
    "diet": "carnivore",
    "period": "early cretaceous",
    "existed": "113 - 110 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "Known for the high spines along its back, which likely supported a ridge of muscle. It was one of the largest predators of the Early Cretaceous.",
    "image": "https://images.unsplash.com/photo-1568249760086-53807530867a?auto=format&fit=crop&q=80&w=800",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b319fa",
    "name": "allosaurus",
    "weight": "2000kg",
    "height": "3m",
    "length": "8.5m",
    "diet": "carnivore",
    "period": "late jurassic",
    "existed": "155 - 145 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "The 'Lion of the Jurassic'. A powerful predator with large claws and a massive skull filled with serrated teeth.",
    "image": "https://images.unsplash.com/photo-1525869916826-972885c91c1e?auto=format&fit=crop&q=80&w=800",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b319fb",
    "name": "ankylosaurus",
    "weight": "6000kg",
    "height": "1.7m",
    "length": "7m",
    "diet": "herbivore",
    "period": "late cretaceous",
    "existed": "68 - 66 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "The ultimate armored dinosaur! It was covered in bony plates and had a massive club at the end of its tail for defense.",
    "image": "https://images.unsplash.com/photo-1620067902055-6b6680a6be1d?auto=format&fit=crop&q=80&w=800&offset=20",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b319fc",
    "name": "brachiosaurus",
    "weight": "56000kg",
    "height": "13m",
    "length": "26m",
    "diet": "herbivore",
    "period": "late jurassic",
    "existed": "154 - 150 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "One of the tallest dinosaurs. Its front legs were longer than its back legs, allowing it to reach the highest tree branches.",
    "image": "https://images.unsplash.com/photo-1505315482312-70b0460c9be0?auto=format&fit=crop&q=80&w=800",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b319fd",
    "name": "diplodocus",
    "weight": "12000kg",
    "height": "4m",
    "length": "27m",
    "diet": "herbivore",
    "period": "late jurassic",
    "existed": "154 - 150 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "Famous for its incredibly long neck and whip-like tail. It was one of the longest land animals to ever live.",
    "image": "https://images.unsplash.com/photo-1516211697506-8360bd795160?auto=format&fit=crop&q=80&w=800&offset=50",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b319fe",
    "name": "spinosaurus",
    "weight": "7000kg",
    "height": "5m",
    "length": "15m",
    "diet": "carnivore",
    "period": "cretaceous",
    "existed": "99 - 93 million years ago",
    "region": "africa",
    "type": "terrestrial/aquatic",
    "description": "A massive predator with a huge sail on its back. It is believed to have been one of the first dinosaurs that could swim and hunt fish.",
    "image": "https://images.unsplash.com/photo-1568249760086-53807530867a?auto=format&fit=crop&q=80&w=800&hue=100",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b319ff",
    "name": "stegosaurus",
    "weight": "4500kg",
    "height": "2.8m",
    "length": "9m",
    "diet": "herbivore",
    "period": "late jurassic",
    "existed": "155 - 150 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "Recognizable by the large bony plates on its back and the four sharp spikes on its tail, called a thagomizer.",
    "image": "https://images.unsplash.com/photo-1525869916826-972885c91c1e?auto=format&fit=crop&q=80&w=800&sepia=30",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b31a00",
    "name": "triceratops",
    "weight": "9000kg",
    "height": "3m",
    "length": "9m",
    "diet": "herbivore",
    "period": "late cretaceous",
    "existed": "68 - 66 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "A three-horned giant with a massive bony frill. It lived at the same time and in the same places as the T-Rex.",
    "image": "https://images.unsplash.com/photo-1517921441013-17726c89c8a1?auto=format&fit=crop&q=80&w=800",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b31a01",
    "name": "tyrannosaurus rex",
    "weight": "8000kg",
    "height": "4m",
    "length": "12.3m",
    "diet": "carnivore",
    "period": "late cretaceous",
    "existed": "68 - 66 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "The 'King of the Tyrant Lizards'. One of the largest and most powerful land predators to ever walk the Earth.",
    "image": "https://images.unsplash.com/photo-1583083527882-4bee9aba2eea?auto=format&fit=crop&q=80&w=800",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b31a02",
    "name": "velociraptor",
    "weight": "15kg",
    "height": "0.5m",
    "length": "2m",
    "diet": "carnivore",
    "period": "late cretaceous",
    "existed": "75 - 71 million years ago",
    "region": "asia",
    "type": "terrestrial",
    "description": "A small but deadly predator. It was covered in feathers and had a sharp, sickle-shaped claw on each foot.",
    "image": "https://images.unsplash.com/photo-1559999141-792646c05f56?auto=format&fit=crop&q=80&w=800&brightness=-20",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b31a03",
    "name": "parasaurolophus",
    "weight": "2500kg",
    "height": "4m",
    "length": "10m",
    "diet": "herbivore",
    "period": "late cretaceous",
    "existed": "76 - 73 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "Famous for the long, curved crest on its head. Scientists think it used this crest to make loud, trumpeting sounds!",
    "image": "https://images.unsplash.com/photo-1516211697506-8360bd795160?auto=format&fit=crop&q=80&w=800&contrast=120",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b31a04",
    "name": "dilophosaurus",
    "weight": "400kg",
    "height": "2m",
    "length": "7m",
    "diet": "carnivore",
    "period": "early jurassic",
    "existed": "193 million years ago",
    "region": "north america",
    "type": "terrestrial",
    "description": "Identified by the two thin crests on its head. Unlike the movies, there is no evidence it spat venom or had a neck frill!",
    "image": "https://images.unsplash.com/photo-1559999141-792646c05f56?auto=format&fit=crop&q=80&w=800&hue=150",
    "isPopular": true
  },
  {
    "_id": "65b018ff4e53acf9a2b31a05",
    "name": "iguanodon",
    "weight": "3000kg",
    "height": "2.7m",
    "length": "10m",
    "diet": "herbivore",
    "period": "early cretaceous",
    "existed": "126 - 122 million years ago",
    "region": "europe",
    "type": "terrestrial",
    "description": "One of the first dinosaurs ever discovered. It had a sharp spike on its thumb, likely used for defense against predators.",
    "image": "https://images.unsplash.com/photo-1505315482312-70b0460c9be0?auto=format&fit=crop&q=80&w=800&exposure=-10",
    "isPopular": true
  }
];